### ISSUE TITLE
UnicodeDecodeError。

### ISSUE THREAD

**Issue by DreamLoveBetty** [ironjr/StreamMultiDiffusion#5]
(venv) D:\Program\StreamMultiDiffusion\demo\semantic_palette>python app.py
Traceback (most recent call last):
  File "D:\Program\StreamMultiDiffusion\demo\semantic_palette\app.py", line 39, in <module>
    import gradio as gr
  File "D:\Program\StreamMultiDiffusion\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "D:\Program\StreamMultiDiffusion\venv\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "D:\Program\StreamMultiDiffusion\venv\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "D:\Program\StreamMultiDiffusion\venv\lib\site-packages\gradio\components\__init__.py", line 40, in <module>
    from gradio.components.multimodal_textbox import MultimodalTextbox
  File "D:\Program\StreamMultiDiffusion\venv\lib\site-packages\gradio\components\multimodal_textbox.py", line 34, in <module>
    class MultimodalTextbox(FormComponent):
  File "D:\Program\StreamMultiDiffusion\venv\lib\site-packages\gradio\component_meta.py", line 198, in __new__
    create_or_modify_pyi(component_class, name, events)
  File "D:\Program\StreamMultiDiffusion\venv\lib\site-packages\gradio\component_meta.py", line 92, in create_or_modify_pyi
    source_code = source_file.read_text()
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1135, in read_text
    return f.read()
c: 'gbk' codec can't decode byte 0xb2 in position 2074: illegal multibyte sequence
----------------------------------------------------------------------------------------------------------------------------------------------------
Additionally, there is no "app. py" in the root directory, only "app. py" in the demo directory?

**Comment by ironjr** [comment]
1. It seems like a gradio bug. I have found similar issue [here](https://github.com/THUDM/ChatGLM3/discussions/1009). It seems like newer version of gradio raises error when opened with non-English environment. Please try this in your venv:
```bash
pip install gradio==4.21.0
```
then run again. If the error persists, please reopen this issue.

2. Thanks for the correction. Just changed the instructions accordingly. If you want to use Semantic Palette app, `cd demo/semantic_palette; python app.py --model "model here"` will do as you have already tried.

**Comment by DreamLoveBetty** [comment]
Okay, let's give it a try now. Thank you for your answer!
