### ISSUE TITLE
why I can't run ?

### ISSUE THREAD

**Issue by wdcww** [ironjr/StreamMultiDiffusion#7]
hello, I'm a newbie and want to ask you some questions

## 1. I followed the  installation steps in the readme.md , create a new environment from scratch.

```bash
(smd) PS E:\github_download\StreamMultiDiffusion> conda list
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h2bbff1b_5
ca-certificates           2024.3.11            haa95532_0
libffi                    3.4.4                hd77b12b_0
openssl                   3.0.13               h2bbff1b_0
pip                       24.0                     pypi_0    pypi
python                    3.10.14              he1021f5_0
setuptools                68.2.2          py310haa95532_0
sqlite                    3.41.2               h2bbff1b_0
tk                        8.6.12               h2bbff1b_0
tzdata                    2024a                h04d1e81_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.41.2          py310haa95532_0
xz                        5.4.6                h8cc25b3_0
zlib                      1.2.13               h8cc25b3_0
```

## Why does the following error appear when running"pip install -r requirements.txt"? 
```bash
(smd) PS E:\github_download\StreamMultiDiffusion> pip install -r requirements.txt
Looking in indexes: https://pypi.ngc.nvidia.com
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
```
## Does my environment require torch to be installed before I can install your package?

---
## 2. Then I changed to an environment that already had <pytorch-2.2.2_cuda12.1_cudnn8_0> installed.

```bash
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "E:\git\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "E:\git\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
Traceback (most recent call last):
  File "E:\github_download\StreamMultiDiffusion\try.py", line 18, in <module>
    import protobuf
ModuleNotFoundError: No module named 'protobuf'
```

```bash
(E:\git) PS E:\github_download\StreamMultiDiffusion> pip install triton protobuf                                    
ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton
```

## but I have " protobuf    3.20.2   pypi_0    pypi " 
```bash
# packages in environment at E:\git:
#
# Name                    Version                   Build  Channel
abseil-cpp                20211102.0           hd77b12b_0
absl-py                   1.4.0            py38haa95532_0
aiofiles                  23.2.1                   pypi_0    pypi
aiohttp                   3.8.5            py38h2bbff1b_0
aiosignal                 1.2.0              pyhd3eb1b0_0
albumentations            1.3.1              pyhd8ed1ab_0    conda-forge
altair                    5.3.0                    pypi_0    pypi
annotated-types           0.6.0                    pypi_0    pypi
anyio                     4.3.0                    pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.3.0                    pypi_0    pypi
asttokens                 2.4.0                    pypi_0    pypi
async-lru                 2.0.4                    pypi_0    pypi
async-timeout             4.0.2            py38haa95532_0
attrs                     23.1.0           py38haa95532_0
babel                     2.14.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
blas                      1.0                         mkl
bleach                    6.1.0                    pypi_0    pypi
blinker                   1.6.2            py38haa95532_0
bottleneck                1.3.5            py38h080aedc_0
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
brotlipy                  0.7.0           py38h2bbff1b_1003
c-ares                    1.19.1               h2bbff1b_0
ca-certificates           2024.3.11            haa95532_0
cachetools                4.2.2              pyhd3eb1b0_0
certifi                   2024.2.2         py38haa95532_0
cffi                      1.15.1           py38h2bbff1b_3
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.0.4            py38haa95532_0
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6            py38haa95532_0
coloredlogs               15.0.1                   pypi_0    pypi
comm                      0.1.4                    pypi_0    pypi
competition               1.0.0.4                  pypi_0    pypi
contourpy                 1.0.5            py38h59b6b97_0
cryptography              41.0.3           py38h3438e0d_0
cuda-cccl                 12.2.140                      0    nvidia
cuda-cudart               12.1.105                      0    nvidia
cuda-cudart-dev           12.1.105                      0    nvidia
cuda-cupti                12.1.105                      0    nvidia
cuda-libraries            12.1.0                        0    nvidia
cuda-libraries-dev        12.1.0                        0    nvidia
cuda-nvrtc                12.1.105                      0    nvidia
cuda-nvrtc-dev            12.1.105                      0    nvidia
cuda-nvtx                 12.1.105                      0    nvidia
cuda-opencl               12.2.140                      0    nvidia
cuda-opencl-dev           12.2.140                      0    nvidia
cuda-profiler-api         12.2.140                      0    nvidia
cuda-python               12.3.0                   pypi_0    pypi
cuda-runtime              12.1.0                        0    nvidia
cycler                    0.11.0             pyhd3eb1b0_0
cython                    3.0.0            py38h2bbff1b_0
cytoolz                   0.12.0           py38h2bbff1b_0
dask-core                 2022.12.1          pyhd8ed1ab_0    conda-forge
debugpy                   1.8.0                    pypi_0    pypi
decorator                 4.4.2              pyhd3eb1b0_0
defusedxml                0.7.1                    pypi_0    pypi
diffusers                 0.18.2           py38h9909e9c_0
diffusers-base            0.18.2           py38h9909e9c_0
diffusers-torch           0.18.2           py38h9909e9c_0
eigen                     3.4.0                h2d74725_0    conda-forge
einops                    0.7.0                    pypi_0    pypi
emoji                     2.11.0                   pypi_0    pypi
enum34                    1.1.10           py38h32f6830_2    conda-forge
exceptiongroup            1.0.4            py38haa95532_0
executing                 2.0.0                    pypi_0    pypi
fastapi                   0.110.1                  pypi_0    pypi
fastjsonschema            2.19.1                   pypi_0    pypi
ffmpeg                    4.2.3                ha925a31_0    conda-forge
ffmpy                     0.3.2                    pypi_0    pypi
filelock                  3.9.0            py38haa95532_0
fire                      0.6.0                    pypi_0    pypi
flatbuffers               24.3.25                  pypi_0    pypi
fonttools                 4.25.0             pyhd3eb1b0_0
fqdn                      1.5.1                    pypi_0    pypi
freetype                  2.12.1               ha860e81_0
frozenlist                1.3.3            py38h2bbff1b_0
fsspec                    2023.9.2           pyh1a96a4e_0    conda-forge
giflib                    5.2.1                h8cc25b3_3
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.37                   pypi_0    pypi
glib                      2.69.1               h5dc1a3c_2
google-auth               2.22.0           py38haa95532_0
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0
gradio                    4.21.0                   pypi_0    pypi
gradio-client             0.12.0                   pypi_0    pypi
grpc-cpp                  1.48.2               hf108199_0
grpcio                    1.48.2           py38hf108199_0
gst-plugins-base          1.18.5               h9e645db_0
gstreamer                 1.18.5               hd78058f_0
h11                       0.14.0                   pypi_0    pypi
hdf5                      1.12.1               h51c971a_3
httpcore                  1.0.5                    pypi_0    pypi
httpx                     0.27.0                   pypi_0    pypi
huggingface_accelerate    0.21.0           py38haa95532_0
huggingface_hub           0.20.3           py38haa95532_0
humanfriendly             10.0                     pypi_0    pypi
icc_rt                    2022.1.0             h6049295_2
icu                       58.2                 ha925a31_3
idna                      3.4              py38haa95532_0
imagecodecs-lite          2019.12.3        py38hbdcd294_5    conda-forge
imageio                   2.31.5             pyh8c1a49c_0    conda-forge
importlib-metadata        6.0.0            py38haa95532_0
importlib_resources       5.2.0              pyhd3eb1b0_1
iniconfig                 1.1.1              pyhd3eb1b0_0
intel-openmp              2023.1.0         h59b6b97_46319
ipykernel                 6.25.2                   pypi_0    pypi
ipython                   8.12.3                   pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.2            py38haa95532_0
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h2bbff1b_1
json5                     0.9.25                   pypi_0    pypi
jsonpointer               2.4                      pypi_0    pypi
jsonschema                4.21.1                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter-client            8.4.0                    pypi_0    pypi
jupyter-core              5.4.0                    pypi_0    pypi
jupyter-events            0.10.0                   pypi_0    pypi
jupyter-lsp               2.2.5                    pypi_0    pypi
jupyter-server            2.14.0                   pypi_0    pypi
jupyter-server-terminals  0.5.3                    pypi_0    pypi
jupyterlab                4.1.6                    pypi_0    pypi
jupyterlab-pygments       0.3.0                    pypi_0    pypi
jupyterlab-server         2.26.0                   pypi_0    pypi
kiwisolver                1.4.4            py38hd77b12b_0
krb5                      1.20.1               h5b6d351_1
lerc                      3.0                  hd77b12b_0
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libclang                  14.0.6          default_hb5a9fac_1
libclang13                14.0.6          default_h8e68704_1
libcublas                 12.1.0.26                     0    nvidia
libcublas-dev             12.1.0.26                     0    nvidia
libcufft                  11.0.2.4                      0    nvidia
libcufft-dev              11.0.2.4                      0    nvidia
libcurand                 10.3.3.141                    0    nvidia
libcurand-dev             10.3.3.141                    0    nvidia
libcusolver               11.4.4.55                     0    nvidia
libcusolver-dev           11.4.4.55                     0    nvidia
libcusparse               12.0.2.55                     0    nvidia
libcusparse-dev           12.0.2.55                     0    nvidia
libdeflate                1.17                 h2bbff1b_1
libffi                    3.4.4                hd77b12b_0
libiconv                  1.16                 h2bbff1b_2
libjpeg-turbo             2.0.0                h196d8e1_0
libnpp                    12.0.2.50                     0    nvidia
libnpp-dev                12.0.2.50                     0    nvidia
libnvjitlink              12.1.105                      0    nvidia
libnvjitlink-dev          12.1.105                      0    nvidia
libnvjpeg                 12.1.1.14                     0    nvidia
libnvjpeg-dev             12.1.1.14                     0    nvidia
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.39               h8cc25b3_0
libpq                     12.15                hb652d5d_1
libprotobuf               3.20.3               h23ce68f_0
libtiff                   4.5.1                hd77b12b_0
libuv                     1.44.2               h2bbff1b_0
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.3.2                hbc33d0d_0
libwebp-base              1.3.2                h2bbff1b_0
libxml2                   2.10.4               h0ad7f3c_1
libxslt                   1.1.37               h2bbff1b_1
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4-c                     1.9.4                h2bbff1b_0
markdown                  3.4.1            py38haa95532_0
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.1            py38h2bbff1b_0
matplotlib                3.7.2            py38haa95532_0
matplotlib-base           3.7.2            py38h4ed8f06_0
matplotlib-inline         0.1.6                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mistune                   3.0.2                    pypi_0    pypi
mkl                       2023.1.0         h6b88ed4_46357
mkl-service               2.4.0            py38h2bbff1b_1
mkl_fft                   1.3.8            py38h2bbff1b_0
mkl_random                1.2.4            py38h59b6b97_0
mpmath                    1.3.0            py38haa95532_0
multidict                 6.0.2            py38h2bbff1b_0
munkres                   1.1.4                      py_0
nbclient                  0.10.0                   pypi_0    pypi
nbconvert                 7.16.3                   pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
nest-asyncio              1.5.8                    pypi_0    pypi
networkx                  3.1              py38haa95532_0
notebook-shim             0.2.4                    pypi_0    pypi
numexpr                   2.8.4            py38h7b80656_1
numpy                     1.24.3           py38h79a8e48_1
numpy-base                1.24.3           py38h8a87ada_1
oauthlib                  3.2.2            py38haa95532_0
onnx                      1.15.0                   pypi_0    pypi
onnx-graphsurgeon         0.5.2                    pypi_0    pypi
onnxruntime               1.16.3                   pypi_0    pypi
opencv                    4.6.0            py38ha36de5b_5
opencv-python             4.8.1.78                 pypi_0    pypi
openjpeg                  2.4.0                h4fc8c34_0
openssl                   1.1.1w               h2bbff1b_0
orjson                    3.10.0                   pypi_0    pypi
overrides                 7.7.0                    pypi_0    pypi
packaging                 23.1             py38haa95532_0
pandas                    1.3.5            py38h6214cd6_0
pandocfilters             1.5.1                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
partd                     1.4.1              pyhd8ed1ab_0    conda-forge
pathlib                   1.0.1            py38haa244fe_7    conda-forge
pcre                      8.45                 hd77b12b_0
peft                      0.10.0                   pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.0.1           py38h045eedc_0
pip                       23.2.1           py38haa95532_0
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              3.10.0           py38haa95532_0
pluggy                    1.0.0            py38haa95532_1
ply                       3.11                     py38_0
polygraphy                0.49.9                   pypi_0    pypi
pooch                     1.7.0            py38haa95532_0
prometheus-client         0.20.0                   pypi_0    pypi
prompt-toolkit            3.0.39                   pypi_0    pypi
protobuf                  3.20.2                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyasn1                    0.4.8              pyhd3eb1b0_0
pyasn1-modules            0.2.8                      py_0
pycparser                 2.21               pyhd3eb1b0_0
pydantic                  2.7.0                    pypi_0    pypi
pydantic-core             2.18.1                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.16.1                   pypi_0    pypi
pyjwt                     2.4.0            py38haa95532_0
pyopenssl                 23.2.0           py38haa95532_0
pyparsing                 3.0.9            py38haa95532_0
pyqt                      5.15.7           py38hd77b12b_0
pyqt5-sip                 12.11.0          py38hd77b12b_0
pyreadline3               3.4.1                    pypi_0    pypi
pysocks                   1.7.1            py38haa95532_0
pytest                    7.4.0            py38haa95532_0
python                    3.8.0                hff0d562_2
python-dateutil           2.8.2              pyhd3eb1b0_0
python-json-logger        2.0.7                    pypi_0    pypi
python-multipart          0.0.9                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytorch                   2.2.2           py3.8_cuda12.1_cudnn8_0    pytorch
pytorch-cuda              12.1                 hde6ce7c_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3.post1     py38haa95532_0
pywavelets                1.4.1            py38h2bbff1b_0
pywin32                   306                      pypi_0    pypi
pywinpty                  2.0.13                   pypi_0    pypi
pyyaml                    6.0              py38h2bbff1b_1
pyzmq                     25.1.1                   pypi_0    pypi
qt-main                   5.15.2               h6072711_9
qt-webengine              5.15.9               h5bd16bc_7
qtwebkit                  5.212                h2bbfb41_5
qudida                    0.0.4              pyhd8ed1ab_0    conda-forge
re2                       2022.04.01           hd77b12b_0
referencing               0.34.0                   pypi_0    pypi
regex                     2023.10.3        py38h2bbff1b_0
requests                  2.31.0           py38haa95532_0
requests-oauthlib         1.3.0                      py_0
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rich                      13.7.1                   pypi_0    pypi
rpds-py                   0.18.0                   pypi_0    pypi
rsa                       4.7.2              pyhd3eb1b0_1
ruff                      0.3.7                    pypi_0    pypi
safetensors               0.4.2                    pypi_0    pypi
scikit-image              0.18.1           py38h4c96930_0    conda-forge
scikit-learn              1.3.1                    pypi_0    pypi
scipy                     1.10.1           py38hdcfc7df_1
seaborn                   0.12.2           py38haa95532_0
semantic-version          2.10.0                   pypi_0    pypi
send2trash                1.8.3                    pypi_0    pypi
setuptools                68.0.0           py38haa95532_0
shellingham               1.5.4                    pypi_0    pypi
sip                       6.6.2            py38hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
smmap                     5.0.1                    pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
stack-data                0.6.3                    pypi_0    pypi
starlette                 0.37.2                   pypi_0    pypi
sympy                     1.11.1           py38haa95532_0
tbb                       2021.8.0             h59b6b97_0
tensorboard               2.10.0           py38haa95532_0
tensorboard-data-server   0.6.1            py38haa95532_0
tensorboard-plugin-wit    1.8.1            py38haa95532_0
tensorboardx              2.2                pyhd3eb1b0_0
termcolor                 2.4.0                    pypi_0    pypi
terminado                 0.18.1                   pypi_0    pypi
thop                      0.1.1-2209072238          pypi_0    pypi
threadpoolctl             3.2.0              pyha21a80b_0    conda-forge
tifffile                  2019.7.26.2              py38_0    conda-forge
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h2bbff1b_0
tokenizers                0.15.2                   pypi_0    pypi
toml                      0.10.2             pyhd3eb1b0_0
tomli                     2.0.1            py38haa95532_0
tomlkit                   0.12.0                   pypi_0    pypi
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
torch                     2.2.0                    pypi_0    pypi
torch-cluster             1.6.3+pt21cu121          pypi_0    pypi
torch-geometric           2.3.1                    pypi_0    pypi
torch-scatter             2.1.2+pt21cu121          pypi_0    pypi
torch-sparse              0.6.18+pt21cu121          pypi_0    pypi
torch-spline-conv         1.2.2+pt21cu121          pypi_0    pypi
torchaudio                2.2.2                    pypi_0    pypi
torchvision               0.17.2                   pypi_0    pypi
tornado                   6.3.3            py38h2bbff1b_0
tqdm                      4.66.1                   pypi_0    pypi
traitlets                 5.11.2                   pypi_0    pypi
transformers              4.39.3                   pypi_0    pypi
typer                     0.12.3                   pypi_0    pypi
types-python-dateutil     2.9.0.20240316           pypi_0    pypi
typing-extensions         4.11.0                   pypi_0    pypi
typing_extensions         4.9.0            py38haa95532_1
ultralytics               8.0.199                  pypi_0    pypi
uri-template              1.3.0                    pypi_0    pypi
urllib3                   1.26.16          py38haa95532_0
uvicorn                   0.29.0                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.8                    pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.7.0                    pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
werkzeug                  2.2.3            py38haa95532_0
wheel                     0.41.2           py38haa95532_0
win_inet_pton             1.1.0            py38haa95532_0
xformers                  0.0.24                   pypi_0    pypi
xz                        5.4.2                h8cc25b3_0
yaml                      0.2.5                he774522_0
yarl                      1.8.1            py38h2bbff1b_0
zipp                      3.11.0           py38haa95532_0
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.5                hd43e919_0

```

---
## And I run app.py 
```bash
(E:\git) PS E:\github_download\StreamMultiDiffusion\demo\semantic_palette> python app.py
```
```bash
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "E:\git\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "E:\git\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
Traceback (most recent call last):
  File "app.py", line 42, in <module>
    from model import StableMultiDiffusionPipeline
  File "../../src\model\__init__.py", line 21, in <module>
    from .stablemultidiffusion_pipeline import StableMultiDiffusionPipeline
  File "../../src\model\stablemultidiffusion_pipeline.py", line 22, in <module>
    from diffusers import LCMScheduler, DDIMScheduler, AutoencoderTiny
ImportError: cannot import name 'LCMScheduler' from 'diffusers' (E:\git\lib\site-packages\diffusers\__init__.py)
```

**Comment by ironjr** [comment]
Thank you for the detailed description of the problem.

1. I think I have messed up with `requirements.txt` while I try to add TensorRT support. I have just reverted the change. So you can now install with `git pull origin main; pip -r requirements.txt`. Thanks for the reporting!
2. The above patch solves this problem, too.
3. Checkpoints are optional. By default, the app automatically downloads the exact same model you see in the [hugging face demo](https://huggingface.co/spaces/ironjr/SemanticPalette). If you want to try the demo with other models, you can download and put any `.safetensors` files like `BlazingDriveV11m.safetensors` (e.g., from [CivitAI](https://civitai.com/)) like `<demo/semantic_palette/checkpoints/BlazingDriveV11m.safetensor>`. Then you may use it by calling the app with `python app.py --model "BlazingDriveV11m.safetensors"`.
4. (cannot import name 'LCMScheduler' from 'diffusers' error) This problem is also related to `requirements.txt`. It means your pytorch-compatible `diffusers` library is outdated to not have `LCMScheduler` class. Please try installing again with the instruction I provided in answer (1).

I just have tried installing this from scratch and it works under my environment settings. You may reopen this issue if any other problems are found. Thanks again for the reporting!

**Comment by wdcww** [comment]
First of all, I really appreciate you replying to me in detail. 


## · Regarding my question 1. & 2. about the environment configuration： 
Your updated requirements.txt can indeed install packages without conflicts,but the CPU version of torch was installed for me.
Although your previous question (#6) provided PyTorch 2.0.1 + cpu, the warning reminded us: xFormers was built for PyTorch 2.0.1+cu118 with CUDA 1108, so I had to switch to the GPU version of torch.
I use this:
```conda install pytorch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 pytorch-cuda=11.8 -c pytorch -c nvidia```

Matching the environment is really torture for me ! ! !


## · For my question 3. about how to run app.py :
you are right !
By default, 
```bash
 python app.py  --height 512 --width 512 --port 8000
```

I downloaded and placed the blazingDrive_V11m.safetensors file into checkpoints/
```bash
(smd) PS E:\github_download\StreamMultiDiffusion\demo\semantic_palette> python app.py --model "blazingDrive_V11m.safetensors" --height 512 --width 512 --port 8000

```

Now it can run, I want to continue studying.

Thank you so much！

**Comment by ironjr** [comment]
Ohh, thank you so much for pointing out!

You can always reopen any issue if you find any trouble.
