### ISSUE TITLE
ImportError: cannot import name 'ForkProcess' from 'multiprocessing.context' (C:\Users\AmDAM\anaconda3\envs\smd\lib\multiprocessing\context.py

### ISSUE THREAD

**Issue by NeoNogin** [ironjr/StreamMultiDiffusion#8]
Followed the instructions on the readme. I'm getting the following error: 

(smd) C:\ai\StreamMultiDiffusion\demo\stream_v2>python app.py --model "lyriel_v16.safetensors" --height 512 --width 512 --port 8000
Traceback (most recent call last):
  File "C:\ai\StreamMultiDiffusion\demo\stream_v2\app.py", line 40, in <module>
    import spaces
  File "C:\Users\AmDAM\anaconda3\envs\smd\lib\site-packages\spaces\__init__.py", line 10, in <module>
    from .zero.decorator import GPU
  File "C:\Users\AmDAM\anaconda3\envs\smd\lib\site-packages\spaces\zero\decorator.py", line 21, in <module>
    from .wrappers import regular_function_wrapper
  File "C:\Users\AmDAM\anaconda3\envs\smd\lib\site-packages\spaces\zero\wrappers.py", line 15, in <module>
    from multiprocessing.context import ForkProcess
ImportError: cannot import name 'ForkProcess' from 'multiprocessing.context' (C:\Users\AmDAM\anaconda3\envs\smd\lib\multiprocessing\context.py)

**Comment by ironjr** [comment]
Thanks for reporting! `import spaces` in the file `app.py` is only used for hugging face space environment and not for the local server. I just removed that line, so please run `git pull origin main` and retry the app.
